use_frameworks!

platform :ios, '8.0'

target 'YJActivityIndicatorView_Example' do
  pod 'YJActivityIndicatorView', :path => '../'

  target 'YJActivityIndicatorView_Tests' do
    inherit! :search_paths

    
  end
end
